### ISSUE TITLE
Failed to Load Extension

### ISSUE THREAD

**Issue by P-Oveisi** [jflam/chat-gpt-jupyter-extension#6]
Hi,

I'm getting this error when trying to load the extension file in chrome:
![image](https://user-images.githubusercontent.com/89212381/224137663-9e8a9d82-de24-43f4-a996-d79a35e91a5e.png)

Any ideas for troubleshooting?

Thanks in advance!

**Comment by wolf00neka** [comment]
you need to unzip, then u will have 2folders unzipped 'build' and 'macOs'
you drag those folders not the ZIP

**Comment by P-Oveisi** [comment]
It's working now, thanks!
